### ISSUE TITLE
PaperTrade dont fill

### ISSUE THREAD

**Issue by LORDofDOOM** [sthewissen/Mynt#59]
I don't know if PaperTrade is a WIP, but should a "PaperTrade" order not always be filled (buy) to get results for proper testing ? 

Currently it will get cleaned/canceled with "CancelUnboughtOrders()" because there is no fill.

**Comment by sthewissen** [comment]
The idea behind the `PaperTradeManager` is that it mimics the `LiveTradeManager` as close as possible to get an idea of what is bought and what isn't. Since no actual orders are placed on an exchange this is obviously not entirely possible. However, just like on an actual exchange your orders may not always be filled. Since you have a few different options when placing a buy order (to buy it for a lower price than the current price) it checks if the price you put the order on got hit after it was placed.

**Comment by LORDofDOOM** [comment]
Thank you for your fast answer. 

I know that there is no "real" fill made, but on other bots a "PaperTrade" is just filled with current value to test e.g. weekly performance or stop loss triggers. 

In our current case I see that the bot want to buy on a strategy but because the order is not filled I cant check exit strategies or triggers.

**Comment by LORDofDOOM** [comment]
To make things less complicated I think the fastest solution is to set the fill to last candle price. Thats not exactly accurate but we can test strategy triggers for sell and trailing stop loss.

Thank you for look into this :-)

**Comment by sthewissen** [comment]
Just pushed a commit to `develop` that should include this behavior. You can give a new enum value called `OrderBehavior.AlwaysFill` to the `PaperTradeManager` constructor. This ensures that your order will be filled within the next SellTimer check :)

**Comment by sthewissen** [comment]
@LORDofDOOM Did you manage to get around to testing this?

**Comment by twixwix** [comment]
It works fine I tested it.

**Comment by sthewissen** [comment]
I'll close this for now, if there's something wrong we can create a new issue.
