### ISSUE TITLE
Find an appropriate license

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/Mynt#8]
This software is currently licensed using the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 license. The intention of this piece of software is to free for personal use. However due to the unregulated nature of the crypto world I want to prevent people from selling this piece of software to unsuspecting people and make money from it that way.

However, due to the fact that this piece of software is mainly used to make money the current license might contradict itself.

**Comment by gabrielvdk** [comment]
From what I have been finding on the InterWebs, no standard license exists for this (apart from Copyright - but that's probably to restrictive). Of course there's debate and different thoughts...

Based on the below I think https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0) fits the most. Especially since it requires derived works from also being open source and the license can't be changed.

_"The license shall not restrict any party from selling or giving away the software as a component of an aggregate software distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale." That's the very first clause of the Open Source Definition. Alternatively: "The freedom to redistribute copies so you can help your neighbor" and "The freedom to distribute copies of your modified versions to others" are freedoms 2 and 3 of the Free Software Definition. – Jörg W Mittag Dec 14 '12 at 16:23_

And:

_First Why? Unless there is a high probability of this happening (in which case, you should be seeing your attorney now anyway, it appears that you are suffering from the I-am-afraid-someone-will-take-from-me syndrome.

In all seriousness, what are you concerned about, and why would someone purchase your code from someone else if it is free from you? And if the value added by the 3rd party is enough to warrant purchasing, why would you want to stop them? In other words, that would be a good thing for you (bigger ecosystem), not a bad thing._
https://softwareengineering.stackexchange.com/questions/179383/open-source-license-that-prevents-re-selling

_If you want to give people the source code, just ship it along. If you want them legally prohibited from redistributing it, well, copyright law already does that — you don't need a special licence, just the usual copyright notice. You'll find it contains text to the effect of “All rights reserved” - one of those rights is the right to redistribute a copyrighted work, which your code is.

Of course you can add further text to clarify things if you want, but unless you are an expert you run the risk of accidentally changing the terms in ways you didn't want. As usual, consult an actual lawyer for actual legal advice._
https://softwareengineering.stackexchange.com/a/79594

Also see: https://softwareengineering.stackexchange.com/questions/232400/is-there-a-software-license-for-personal-use-only-and-against-any-derivative-w

**Comment by sthewissen** [comment]
Thanks for that! We can put it under AGPL if that's ok with you guys? What I'd love most is if we can continue to develop on this and simply make a kickass, useful product. I also checked with @jgsnijders if it would be a good idea to hook up on Telegram and talk about this project if you want? My handle there is @cryptotoolsnet.
